template: Hello, %s!
defaultName: Stranger

exchanges:
  'org.knowm.xchange.poloniex.PoloniexExchange':
    name: Poloniex
    key: 0YLYH5CW-ZFBDX4T6-0V74ZN74-D5BW5LBV
    secret: 7c565d4e144fdcf8f707ece71a68a377980ceafa6a66757121fefa2a1db8942d4a0a217263808bec0922be571de7835b39c4ba6ebbe1ae005bf642223ee26526
    taker: 0.25
    maker: 0.15
  'org.knowm.xchange.anx.v2.ANXExchange':
    name: ANXPRO
    key: e0f2fa0f-0110-454d-99a5-4da24607daf0
    secret: /vqfBtEO7k0BburlUkG3Yb47D9LLtiUEJQggKHlO2CwSxTMj2tR2hOSsL6RtVyLxptp/TYiaPL4XwqFGGKisAg==
    taker: 0.6
    maker: 0.3
  'org.knowm.xchange.bittrex.v1.BittrexExchange':
    name: Bittrex
    key: xxxx
    secret: xxxx
    taker: 0.25
    maker: 0.25


