template: Hello, %s!
defaultName: Stranger

exchanges:
  'org.knowm.xchange.poloniex.PoloniexExchange':
    key: 0YLYH5CW-ZFBDX4T6-0V74ZN74-D5BW5LBV
    secret: 7c565d4e144fdcf8f707ece71a68a377980ceafa6a66757121fefa2a1db8942d4a0a217263808bec0922be571de7835b39c4ba6ebbe1ae005bf642223ee26526
  'org.knowm.xchange.bittrex.v1.BittrexExchange':
    key: xxxx
    secret: xxxx
  'org.knowm.xchange.anx.v2.ANXExchange':
    key: xxxx
    secret: xxxx
